Repository googleapis/java-translate, pull requests merged in 2020-09, with the labels that each got.

#285 chore: regenerate templates
  .github/CODEOWNERS
  .github/workflows/auto-release.yaml
  .kokoro/release/stage.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#286 samples: increased timeout up to 450 secs since batch LRO reaches 5 m…
  samples/snippets/src/main/java/com/example/translate/BatchTranslateText.java
  samples/snippets/src/main/java/com/example/translate/BatchTranslateTextWithGlossary.java
  samples/snippets/src/main/java/com/example/translate/BatchTranslateTextWithGlossaryAndModel.java
  samples/snippets/src/main/java/com/example/translate/BatchTranslateTextWithModel.java
Labels: cla: yes

#289 chore: regenerate README
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#291 build(java): use yoshi-approver token for auto-approve
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#290 chore: add repo settings configuration
  .github/sync-repo-settings.yaml
Labels: api: translate, automerge, cla: yes

#293 chore(ci): skip autorelease workflow on non-release PRs
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: translate, automerge, cla: yes, context: full

#294 chore(ci): verify autorelease release PR content has changes
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#295 chore(java): use separate autosynth job for README
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  synth.metadata
Labels: api: translate, automerge, cla: yes, context: full

#296 build: rename samples lint workflow to checkstyle to disambiguate branch protection with unit lint
  .github/workflows/samples.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
