Repository googleapis/java-translate, pull requests merged in 2020-08, with the labels that each got.

#255 cleanup: removes unused kokoro config files
  .kokoro/continuous/dependencies.cfg
  .kokoro/continuous/integration.cfg
  .kokoro/continuous/java11.cfg
  .kokoro/continuous/java7.cfg
  .kokoro/continuous/java8-osx.cfg
  .kokoro/continuous/java8-win.cfg
  .kokoro/continuous/lint.cfg
  .kokoro/continuous/propose_release.cfg
  .kokoro/continuous/samples.cfg
  .kokoro/nightly/dependencies.cfg
  .kokoro/nightly/lint.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#256 build: update dependencies check to only check for runtime and compile scopes
  .kokoro/dependencies.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#260 chore: regenerate README
  README.md
  synth.metadata
Labels: cla: yes, context: none

#262 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#263 chore: regenerate sample list
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#274 fix: increase batch translate timeout to 300
  samples/snippets/src/main/java/com/example/translate/BatchTranslateText.java
  samples/snippets/src/main/java/com/example/translate/BatchTranslateTextWithGlossary.java
  samples/snippets/src/main/java/com/example/translate/BatchTranslateTextWithGlossaryAndModel.java
  samples/snippets/src/main/java/com/example/translate/BatchTranslateTextWithModel.java
Labels: cla: yes
