Repository googleapis/java-translate, pull requests merged in 2020-07, with the labels that each got.

#236 ci(java): run dependency test on Java 8 and 11
  .github/workflows/ci.yaml
  .kokoro/dependencies.sh
  pom.xml
  synth.metadata
Labels: automerge, cla: yes, context: full

#242 fix: replace get("model") with translationPb.getModel()
  google-cloud-translate/src/main/java/com/google/cloud/translate/Translation.java
  google-cloud-translate/src/test/java/com/google/cloud/translate/TranslationTest.java
Labels: automerge, cla: yes

#243 fix: use rest api for detect and listSupportedLanguages
  google-cloud-translate/src/main/java/com/google/cloud/translate/spi/v2/HttpTranslateRpc.java
Labels: automerge, cla: yes

#250 chore: regenerate README
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#252 chore(docs): add cloud-RAD
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#251 docs: corrects spelling of build dependency adds backticks in docstring to smooth doc generation
  proto-google-cloud-translate-v3/src/main/java/com/google/cloud/translate/v3/OutputConfig.java
  proto-google-cloud-translate-v3/src/main/java/com/google/cloud/translate/v3/OutputConfigOrBuilder.java
  proto-google-cloud-translate-v3/src/main/proto/google/cloud/translate/v3/translation_service.proto
  proto-google-cloud-translate-v3beta1/src/main/java/com/google/cloud/translate/v3beta1/OutputConfig.java
  proto-google-cloud-translate-v3beta1/src/main/java/com/google/cloud/translate/v3beta1/OutputConfigOrBuilder.java
  proto-google-cloud-translate-v3beta1/src/main/proto/google/cloud/translate/v3beta1/translation_service.proto
  synth.metadata
Labels: automerge, cla: yes, context: full
