Repository googleapis/java-translate, pull requests merged in 2020-11, with the labels that each got.

#338 chore(java): use production staging bucket
  .kokoro/release/publish_javadoc.cfg
  synth.metadata
Labels: api: translate, automerge, cla: yes, context: full

#341 chore(java): ignore return code 28 in README autosynth job
  .kokoro/readme.sh
  synth.metadata
Labels: api: translate, automerge, cla: yes, context: full

#342 build(java): use code-suggester v1 tag rather than full semver
  .github/workflows/formatting.yaml
  synth.metadata
Labels: api: translate, automerge, cla: yes, context: full

#344 deps: update dependency com.google.cloud:google-cloud-shared-dependencies to v0.15.0
  pom.xml
Labels: api: translate, automerge, cla: yes

#348 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: translate, automerge, cla: yes

#346 build(java): use actions/github-script v3 tag rather than full semver
  .github/workflows/approve-readme.yaml
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: translate, automerge, cla: yes, context: full

#352 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: translate, automerge, cla: yes

#353 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: translate, automerge, cla: yes

#354 chore(java): retry staging portion of the release with backoff
  .kokoro/common.sh
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: translate, automerge, cla: yes, context: full

#355 build(java): enable blunderbuss for samples
  .github/blunderbuss.yml
  synth.metadata
Labels: api: translate, automerge, cla: yes, context: full, samples
