Repository googleapis/java-translate, pull requests merged in 2020-06, with the labels that each got.

#188 fix: restore GAPIC v2 retry configs
  google-cloud-translate/src/main/java/com/google/cloud/translate/v3/TranslationServiceClient.java
  google-cloud-translate/src/main/java/com/google/cloud/translate/v3/TranslationServiceSettings.java
  google-cloud-translate/src/main/java/com/google/cloud/translate/v3/stub/GrpcTranslationServiceStub.java
  google-cloud-translate/src/main/java/com/google/cloud/translate/v3/stub/TranslationServiceStub.java
  google-cloud-translate/src/main/java/com/google/cloud/translate/v3/stub/TranslationServiceStubSettings.java
  google-cloud-translate/src/main/java/com/google/cloud/translate/v3beta1/TranslationServiceClient.java
  google-cloud-translate/src/main/java/com/google/cloud/translate/v3beta1/TranslationServiceSettings.java
  google-cloud-translate/src/main/java/com/google/cloud/translate/v3beta1/stub/GrpcTranslationServiceStub.java
  google-cloud-translate/src/main/java/com/google/cloud/translate/v3beta1/stub/TranslationServiceStub.java
  google-cloud-translate/src/main/java/com/google/cloud/translate/v3beta1/stub/TranslationServiceStubSettings.java
  google-cloud-translate/src/test/java/com/google/cloud/translate/v3/TranslationServiceClientTest.java
  google-cloud-translate/src/test/java/com/google/cloud/translate/v3beta1/TranslationServiceClientTest.java
  synth.metadata
Labels: automerge, cla: yes, context: full

#201 chore(java_templates): add default CODEOWNERS files for samples reviews
  .github/CODEOWNERS
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: partial

#203 chore: turn on renovate-bot master issue for java repos
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#205 build(java): skip lint on samples directory
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#210 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#214 ci: switch to secret manager for sample/integration tests
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/integration.cfg
  .kokoro/presubmit/samples.cfg
  .kokoro/trampoline.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#220 feat(deps): adopt flatten plugin and google-cloud-shared-dependencies
  .gitignore
  google-cloud-translate/pom.xml
  grpc-google-cloud-translate-v3/pom.xml
  grpc-google-cloud-translate-v3beta1/pom.xml
  pom.xml
  proto-google-cloud-translate-v3/pom.xml
  proto-google-cloud-translate-v3beta1/pom.xml
Labels: cla: yes

#219 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#228 fix: migrate to grpc_service_config
  README.md
  google-cloud-translate/src/main/java/com/google/cloud/translate/v3/TranslationServiceClient.java
  google-cloud-translate/src/main/java/com/google/cloud/translate/v3/TranslationServiceSettings.java
  google-cloud-translate/src/main/java/com/google/cloud/translate/v3/stub/GrpcTranslationServiceStub.java
  google-cloud-translate/src/main/java/com/google/cloud/translate/v3/stub/TranslationServiceStub.java
  google-cloud-translate/src/main/java/com/google/cloud/translate/v3/stub/TranslationServiceStubSettings.java
  google-cloud-translate/src/main/java/com/google/cloud/translate/v3beta1/TranslationServiceClient.java
  google-cloud-translate/src/main/java/com/google/cloud/translate/v3beta1/TranslationServiceSettings.java
  google-cloud-translate/src/main/java/com/google/cloud/translate/v3beta1/stub/GrpcTranslationServiceStub.java
  google-cloud-translate/src/main/java/com/google/cloud/translate/v3beta1/stub/TranslationServiceStub.java
  google-cloud-translate/src/main/java/com/google/cloud/translate/v3beta1/stub/TranslationServiceStubSettings.java
  google-cloud-translate/src/test/java/com/google/cloud/translate/v3/TranslationServiceClientTest.java
  google-cloud-translate/src/test/java/com/google/cloud/translate/v3beta1/TranslationServiceClientTest.java
  synth.metadata
Labels: automerge, cla: yes, context: partial

#235 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none
