Repository googleapis/java-translate, pull requests merged in 2020-10, with the labels that each got.

#298 build(java): readme.sh should be executable
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#297 samples: Translate flaky tests
  samples/snippets/src/main/java/com/example/translate/BatchTranslateText.java
  samples/snippets/src/main/java/com/example/translate/BatchTranslateTextWithGlossary.java
  samples/snippets/src/main/java/com/example/translate/BatchTranslateTextWithGlossaryAndModel.java
  samples/snippets/src/main/java/com/example/translate/BatchTranslateTextWithModel.java
  samples/snippets/src/test/java/com/example/translate/BatchTranslateTextTests.java
  samples/snippets/src/test/java/com/example/translate/BatchTranslateTextWithGlossaryAndModelTests.java
  samples/snippets/src/test/java/com/example/translate/BatchTranslateTextWithGlossaryTests.java
  samples/snippets/src/test/java/com/example/translate/BatchTranslateTextWithModelTests.java
  samples/snippets/src/test/java/com/example/translate/Retry.java
Labels: api: translate, automerge, cla: yes, samples

#312 ci(java): restrict presubmit samples ITs to only snapshot
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#313 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#316 build(java): auto-approve README regeneration
  .github/workflows/approve-readme.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#319 build(java): enable snippet-bot
  .github/snippet-bot.yml
  synth.metadata
Labels: automerge, cla: yes, context: full

#320 chore: clean up and update renovate.json
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#315 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: translate, automerge, cla: yes

#323 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#324 chore: regenerate common templates
  .kokoro/release/publish_javadoc.sh
  CODE_OF_CONDUCT.md
  synth.metadata
Labels: api: translate, automerge, cla: yes, context: full

#327 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#328 chore(ci): fix typo in restrict presubmit samples ITs to only snapshot
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#332 chore(java): enable generated-files-bot
  .github/generated-files-bot.yml
  synth.metadata
Labels: automerge, cla: yes, context: full

#330 feat: use setModel as rest api already support it
  google-cloud-translate/src/main/java/com/google/cloud/translate/spi/v2/HttpTranslateRpc.java
  google-cloud-translate/src/test/java/com/google/cloud/translate/TranslateImplTest.java
Labels: api: translate, cla: yes

#334 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#336 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#337 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes
