Repository googleapis/java-translate, pull requests merged in 2021-03, with the labels that each got.

#449 feat(generator): update protoc to v3.15.3
  proto-google-cloud-translate-v3/clirr-ignored-differences.xml
  proto-google-cloud-translate-v3/src/main/java/com/google/cloud/translate/v3/DetectLanguageRequest.java
  proto-google-cloud-translate-v3/src/main/java/com/google/cloud/translate/v3/DetectLanguageRequestOrBuilder.java
  proto-google-cloud-translate-v3beta1/clirr-ignored-differences.xml
  proto-google-cloud-translate-v3beta1/src/main/java/com/google/cloud/translate/v3beta1/DetectLanguageRequest.java
  proto-google-cloud-translate-v3beta1/src/main/java/com/google/cloud/translate/v3beta1/DetectLanguageRequestOrBuilder.java
  synth.metadata
Labels: api: translate, automerge, cla: yes, context: full

#455 chore: remove docLava v2 doc generation
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: api: translate, automerge, cla: yes, context: full

#458 chore(release): update Java microgenerator to 1.0.1
  google-cloud-translate/src/main/java/com/google/cloud/translate/v3/TranslationServiceClient.java
  google-cloud-translate/src/main/java/com/google/cloud/translate/v3/TranslationServiceSettings.java
  google-cloud-translate/src/main/java/com/google/cloud/translate/v3/package-info.java
  google-cloud-translate/src/main/java/com/google/cloud/translate/v3/stub/GrpcTranslationServiceCallableFactory.java
  google-cloud-translate/src/main/java/com/google/cloud/translate/v3/stub/GrpcTranslationServiceStub.java
  google-cloud-translate/src/main/java/com/google/cloud/translate/v3/stub/TranslationServiceStub.java
  google-cloud-translate/src/main/java/com/google/cloud/translate/v3/stub/TranslationServiceStubSettings.java
  google-cloud-translate/src/main/java/com/google/cloud/translate/v3beta1/TranslationServiceClient.java
  google-cloud-translate/src/main/java/com/google/cloud/translate/v3beta1/TranslationServiceSettings.java
  google-cloud-translate/src/main/java/com/google/cloud/translate/v3beta1/package-info.java
  google-cloud-translate/src/main/java/com/google/cloud/translate/v3beta1/stub/GrpcTranslationServiceCallableFactory.java
  google-cloud-translate/src/main/java/com/google/cloud/translate/v3beta1/stub/GrpcTranslationServiceStub.java
  google-cloud-translate/src/main/java/com/google/cloud/translate/v3beta1/stub/TranslationServiceStub.java
  google-cloud-translate/src/main/java/com/google/cloud/translate/v3beta1/stub/TranslationServiceStubSettings.java
  google-cloud-translate/src/test/java/com/google/cloud/translate/v3/MockTranslationService.java
  google-cloud-translate/src/test/java/com/google/cloud/translate/v3/MockTranslationServiceImpl.java
  google-cloud-translate/src/test/java/com/google/cloud/translate/v3/TranslationServiceClientTest.java
  google-cloud-translate/src/test/java/com/google/cloud/translate/v3beta1/MockTranslationService.java
  google-cloud-translate/src/test/java/com/google/cloud/translate/v3beta1/MockTranslationServiceImpl.java
  google-cloud-translate/src/test/java/com/google/cloud/translate/v3beta1/TranslationServiceClientTest.java
  proto-google-cloud-translate-v3/src/main/java/com/google/cloud/translate/v3/GlossaryName.java
  proto-google-cloud-translate-v3/src/main/java/com/google/cloud/translate/v3/LocationName.java
  proto-google-cloud-translate-v3beta1/src/main/java/com/google/cloud/translate/v3beta1/GlossaryName.java
  proto-google-cloud-translate-v3beta1/src/main/java/com/google/cloud/translate/v3beta1/LocationName.java
  synth.metadata
Labels: api: translate, automerge, cla: yes, context: full

#459 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: translate, automerge, cla: yes

#461 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: translate, automerge, cla: yes

#462 chore: copy README to docfx-yml dir
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: translate, automerge, cla: yes, context: full

#463 chore: update gax-java dependency to 1.62
  grpc-google-cloud-translate-v3/src/main/java/com/google/cloud/translate/v3/TranslationServiceGrpc.java
  grpc-google-cloud-translate-v3beta1/src/main/java/com/google/cloud/translate/v3beta1/TranslationServiceGrpc.java
  synth.metadata
Labels: api: translate, automerge, cla: yes, context: full

#464 chore: adding new output for each test so that the following issue wo…
  samples/snippets/src/test/java/com/example/translate/BatchTranslateTextWithGlossaryAndModelTests.java
  samples/snippets/src/test/java/com/example/translate/BatchTranslateTextWithGlossaryTests.java
  samples/snippets/src/test/java/com/example/translate/BatchTranslateTextWithModelTests.java
Labels: api: translate, cla: yes

#467 build(java): update autorelease title check in response to the new multi release branch changes
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: translate, automerge, cla: yes, context: full

#469 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: translate, automerge, cla: yes

#473 chore: update java microgenerator to 1.0.2 Adds request initialization to sample code
  google-cloud-translate/src/main/java/com/google/cloud/translate/v3/TranslationServiceClient.java
  google-cloud-translate/src/main/java/com/google/cloud/translate/v3beta1/TranslationServiceClient.java
  google-cloud-translate/src/test/java/com/google/cloud/translate/v3/MockTranslationServiceImpl.java
  google-cloud-translate/src/test/java/com/google/cloud/translate/v3beta1/MockTranslationServiceImpl.java
  synth.metadata
Labels: api: translate, automerge, cla: yes, context: full, samples

#475 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: translate, automerge, cla: yes

#477 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: translate, automerge, cla: yes

#479 chore(java): detect sample-secrets in build.sh
  .kokoro/build.sh
  synth.metadata
Labels: api: translate, build.sh, cla: yes, context: full, in, sample-secrets, samples

#480 chore: remove staging bucket v2
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: api: translate, automerge, cla: yes, context: full
