Repository googleapis/java-translate, pull requests merged in 2021-05, with the labels that each got.

#516 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: translate, automerge, cla: yes, context: none

#518 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: translate, automerge, cla: yes, context: full

#527 chore: removed glossary from setup and teardown, Replaced with predef…
  samples/snippets/src/main/java/com/example/translate/BatchTranslateTextWithGlossary.java
  samples/snippets/src/main/java/com/example/translate/BatchTranslateTextWithGlossaryAndModel.java
  samples/snippets/src/test/java/com/example/translate/BatchTranslateTextWithGlossaryAndModelTests.java
  samples/snippets/src/test/java/com/example/translate/BatchTranslateTextWithGlossaryTests.java
  samples/snippets/src/test/java/com/example/translate/GetGlossaryTests.java
  samples/snippets/src/test/java/com/example/translate/ListGlossariesTests.java
  samples/snippets/src/test/java/com/example/translate/TranslateTextWithGlossaryAndModelTests.java
  samples/snippets/src/test/java/com/example/translate/TranslateTextWithGlossaryTests.java
Labels: api: translate, automerge, cla: yes

#528 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: translate, automerge, cla: yes

#533 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: translate, automerge, cla: yes

#535 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: translate, automerge, cla: yes, context: full

#536 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: translate, automerge, cla: yes

#538 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: translate, automerge, cla: yes

#539 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: translate, automerge, cla: yes, context: full

#542 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: translate, automerge, cla: yes, context: full

#540 chore: migrate to owlbot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  google-cloud-translate-bom/pom.xml
  google-cloud-translate/pom.xml
  owlbot.py
  pom.xml
  samples/snippets/src/test/java/com/example/translate/BatchTranslateTextTests.java
  samples/snippets/src/test/java/com/example/translate/BatchTranslateTextWithModelTests.java
  synth.py
  versions.txt
Labels: api: translate, automerge, cla: yes

#549 chore: regenerate README
  .github/generated-files-bot.yml
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: translate, automerge, cla: yes
