Repository googleapis/java-translate, pull requests merged in 2021-06, with the labels that each got.

#554 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: translate, automerge, cla: yes

#560 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: translate, automerge, cla: yes

#553 samples: changed AutoML model ID
  samples/snippets/src/test/java/com/example/translate/BatchTranslateTextWithGlossaryAndModelTests.java
  samples/snippets/src/test/java/com/example/translate/BatchTranslateTextWithModelTests.java
  samples/snippets/src/test/java/com/example/translate/TranslateTextWithGlossaryAndModelTests.java
  samples/snippets/src/test/java/com/example/translate/TranslateTextWithModelTests.java
Labels: api: translate, cla: yes, samples

#559 chore: fix regex in .OwlBot.yaml
  .github/.OwlBot.yaml
Labels: api: translate, automerge, cla: yes

#569 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: translate, automerge, cla: yes

#577 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: translate, automerge, cla: yes

#582 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: translate, automerge, cla: yes

#584 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: translate, automerge, cla: yes

#587 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: translate, automerge, cla: yes

#589 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: translate, automerge, cla: yes

#585 chore: fix batch test
  samples/snippets/src/test/java/com/example/translate/BatchTranslateTextTests.java
  samples/snippets/src/test/java/com/example/translate/BatchTranslateTextWithGlossaryAndModelTests.java
  samples/snippets/src/test/java/com/example/translate/BatchTranslateTextWithGlossaryTests.java
  samples/snippets/src/test/java/com/example/translate/BatchTranslateTextWithModelTests.java
Labels: api: translate, cla: yes

#593 chore: Fix batch tests
  samples/snippets/src/test/java/com/example/translate/BatchTranslateTextTests.java
  samples/snippets/src/test/java/com/example/translate/BatchTranslateTextWithGlossaryAndModelTests.java
  samples/snippets/src/test/java/com/example/translate/BatchTranslateTextWithGlossaryTests.java
  samples/snippets/src/test/java/com/example/translate/BatchTranslateTextWithModelTests.java
Labels: api: translate, cla: yes

#599 chore: refactered batch tests
  samples/snippets/src/test/java/com/example/translate/BatchTranslateTextTests.java
  samples/snippets/src/test/java/com/example/translate/BatchTranslateTextWithGlossaryAndModelTests.java
  samples/snippets/src/test/java/com/example/translate/BatchTranslateTextWithGlossaryTests.java
  samples/snippets/src/test/java/com/example/translate/BatchTranslateTextWithModelTests.java
Labels: api: translate, cla: yes
