Repository googleapis/java-translate, pull requests merged in 2021-02, with the labels that each got.

#407 chore: Re-generated to pick up changes from synthtool.
  .github/workflows/ci.yaml
  .kokoro/linkage-monitor.sh
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: translate, cla: yes, context: partial

#408 build(java): update autorelease branch name check
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: translate, cla: yes, context: full

#410 chore: Re-generated to pick up changes from synthtool.
  .kokoro/release/publish_javadoc11.cfg
  LICENSE
  synth.metadata
Labels: automerge, cla: yes, context: full

#413 docs: generate sample code in the Java microgenerator
  google-cloud-translate/src/main/java/com/google/cloud/translate/v3/TranslationServiceClient.java
  google-cloud-translate/src/main/java/com/google/cloud/translate/v3/package-info.java
  google-cloud-translate/src/main/java/com/google/cloud/translate/v3beta1/TranslationServiceClient.java
  google-cloud-translate/src/main/java/com/google/cloud/translate/v3beta1/package-info.java
  synth.metadata
Labels: api: translate, automerge, cla: yes, context: full, samples

#415 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: translate, automerge, cla: yes

#416 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: translate, automerge, cla: yes

#417 build(java): update autorelease script
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: translate, automerge, cla: yes, context: full

#425 fix: downcase translated text in Integration Test
  google-cloud-translate/src/test/java/com/google/cloud/translate/it/ITTranslateTest.java
Labels: api: translate, automerge, cla: yes

#428 ci: linkage monitor CI job to use build.sh chore: update cloud-rad buckets
  .github/workflows/ci.yaml
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: translate, automerge, cla: yes, context: full

#427 chore: update gapic-generator-java to 0.0.20
  google-cloud-translate/src/main/java/com/google/cloud/translate/v3/stub/GrpcTranslationServiceStub.java
  google-cloud-translate/src/main/java/com/google/cloud/translate/v3beta1/stub/GrpcTranslationServiceStub.java
  google-cloud-translate/src/test/java/com/google/cloud/translate/v3/MockTranslationServiceImpl.java
  google-cloud-translate/src/test/java/com/google/cloud/translate/v3beta1/MockTranslationServiceImpl.java
  synth.metadata
Labels: api: translate, automerge, cla: yes, context: full

#429 build: skip Maven download logs
  .kokoro/build.sh
  synth.metadata
Labels: api: translate, automerge, cla: yes, context: full

#430 build: reduce download junk in log files
  .kokoro/build.sh
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: translate, automerge, cla: yes, context: full

#432 chore: release gapic-generator-java v0.0.21 with gapic_metadata.json support
  google-cloud-translate/src/main/java/com/google/cloud/translate/v3/gapic_metadata.json
  google-cloud-translate/src/main/java/com/google/cloud/translate/v3beta1/gapic_metadata.json
  synth.metadata
Labels: api: translate, automerge, cla: yes, context: full

#436 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: translate, automerge, cla: yes

#439 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: translate, automerge, cla: yes

#440 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: translate, automerge, cla: yes

#379 refactor(samples): restore stdout to original state after test
  samples/snippets/src/test/java/com/example/translate/CreateGlossaryTests.java
  samples/snippets/src/test/java/com/example/translate/DeleteGlossaryTests.java
  samples/snippets/src/test/java/com/example/translate/DetectLanguageTests.java
  samples/snippets/src/test/java/com/example/translate/GetGlossaryTests.java
  samples/snippets/src/test/java/com/example/translate/GetSupportedLanguagesForTargetTests.java
  samples/snippets/src/test/java/com/example/translate/GetSupportedLanguagesTests.java
  samples/snippets/src/test/java/com/example/translate/ListGlossariesTests.java
  samples/snippets/src/test/java/com/example/translate/QuickstartSampleIT.java
  samples/snippets/src/test/java/com/example/translate/TranslateTextTests.java
  samples/snippets/src/test/java/com/example/translate/TranslateTextWithGlossaryAndModelTests.java
  samples/snippets/src/test/java/com/example/translate/TranslateTextWithGlossaryTests.java
  samples/snippets/src/test/java/com/example/translate/TranslateTextWithModelTests.java
Labels: api: translate, cla: yes, samples

#442 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: translate, automerge, cla: yes

#448 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: translate, automerge, cla: yes
